author: Nadri
title: Nadri's musings

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Use upstream minima instead of GitHub Page's outdated version.
remote_theme: jekyll/minima
